#!/bin/bash

# Check the current mapping for keycode 22
result=$(xmodmap -pke | grep "keycode  22 = backslash bar backslash bar")

if [ -n "$result" ]; then
    # If result is not empty, remap keycode 51 and keycode 22
    xmodmap -e "keycode 51 = backslash bar backslash bar"
    xmodmap -e "keycode 22 = BackSpace BackSpace BackSpace BackSpace"
else
    # If result is empty, remap keycode 51 and keycode 22
    xmodmap -e "keycode 51 = BackSpace BackSpace BackSpace BackSpace"
    xmodmap -e "keycode 22 = backslash bar backslash bar"
fi
